.TH "/Users/inflightit/Desktop/coisas/aula_ead/trabalhoPratico/models Directory Reference" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/inflightit/Desktop/coisas/aula_ead/trabalhoPratico/models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBrentals\&.c\fP"
.br
.RI "File containing the functions to manage the rentals\&. "
.ti -1c
.RI "file \fBrentals\&.h\fP"
.br
.RI "File containing the functions to manage the rentals\&. "
.ti -1c
.RI "file \fBroutes\&.c\fP"
.br
.RI "File containing the routes functions\&. "
.ti -1c
.RI "file \fBroutes\&.h\fP"
.br
.RI "File containing the functions to manage the routes\&. "
.ti -1c
.RI "file \fBuser\&.c\fP"
.br
.RI "File containing the functions to manage the users\&. "
.ti -1c
.RI "file \fBuser\&.h\fP"
.br
.RI "File containing the functions to manage the users\&. "
.ti -1c
.RI "file \fBvehicle\&.c\fP"
.br
.RI "File containing the vehicle functions\&. "
.ti -1c
.RI "file \fBvehicle\&.h\fP"
.br
.RI "File containing the functions to manage the vehicles\&. "
.in -1c
