.TH "Adj" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adj
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <routes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcod\fP"
.br
.ti -1c
.RI "float \fBdist\fP"
.br
.ti -1c
.RI "struct \fBAdj\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de uma Adjacência\&. 
.SH "Field Documentation"
.PP 
.SS "int cod"
Código da Adjacência 
.SS "float dist"
ValueDistance 
.SS "struct \fBAdj\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
