.TH "AdjFile" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AdjFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <routes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcodOrigin\fP"
.br
.ti -1c
.RI "int \fBcodDestiny\fP"
.br
.ti -1c
.RI "float \fBweight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura de uma Adjacência para Ficheiro 
.SH "Field Documentation"
.PP 
.SS "int codDestiny"
Código da Adjacência 
.SS "int codOrigin"

.SS "float weight"
ValueDistance 

.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
