.TH "Best" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Best
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <routes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdistance\fP [\fBMAX\fP]"
.br
.ti -1c
.RI "int \fBanteriores\fP [\fBMAX\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int befores[\fBMAX\fP]"

.SS "int distance[\fBMAX\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
