.TH "/Users/inflightit/Desktop/coisas/aula_ead/trabalhoPratico/main.c" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/inflightit/Desktop/coisas/aula_ead/trabalhoPratico/main.c \- File containing the main function\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include '\&./models/user\&.h'\fP
.br
\fC#include '\&./models/vehicle\&.h'\fP
.br
\fC#include '\&./models/rentals\&.h'\fP
.br
\fC#include '\&./models/routes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "The main function of the program\&. "
.in -1c
.SH "Detailed Description"
.PP 
File containing the main function\&. 

This file contains the main function that initializes the program and calls the necessary functions to manipulate user, vehicle, and rent data\&.
.PP
\fBAuthor\fP
.RS 4
João Pereira 
.RE
.PP
\fBDate\fP
.RS 4
2023-03-18 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
The main function of the program\&. This function initializes the program and calls the necessary functions to manipulate user, vehicle, and rent data\&.
.PP
\fBReturns\fP
.RS 4
0 if the program runs successfully 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
