.TH "/Users/inflightit/Desktop/coisas/aula_ead/trabalhoPratico/README.md" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/inflightit/Desktop/coisas/aula_ead/trabalhoPratico/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
