.TH "Rent" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rentals\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "char \fBvehicleRegistration\fP [50]"
.br
.ti -1c
.RI "int \fBuserNif\fP"
.br
.ti -1c
.RI "int \fBtimeInMinutes\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int id"

.SS "int timeInMinutes"

.SS "int userNif"

.SS "char vehicleRegistration[50]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
