.TH "RentList" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RentList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rentals\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRent\fP \fBrent\fP"
.br
.ti -1c
.RI "\fBRentList\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBRentList\fP* next"

.SS "\fBRent\fP rent"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
