.TH "User" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
User
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <user\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnif\fP"
.br
.ti -1c
.RI "char \fBname\fP [50]"
.br
.ti -1c
.RI "char \fBemail\fP [50]"
.br
.ti -1c
.RI "int \fBphone\fP"
.br
.ti -1c
.RI "int \fBzip\fP"
.br
.ti -1c
.RI "char \fBpassword\fP [50]"
.br
.ti -1c
.RI "int \fBwallet\fP"
.br
.ti -1c
.RI "bool \fBisManager\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char email[50]"

.SS "bool isManager"

.SS "char name[50]"

.SS "int nif"

.SS "char password[50]"

.SS "int phone"

.SS "int wallet"

.SS "int zip"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
