.TH "UserList" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UserList
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <user\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBUser\fP \fBuser\fP"
.br
.ti -1c
.RI "\fBUserList\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBUserList\fP* next"

.SS "\fBUser\fP user"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
