.TH "VertexFile" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VertexFile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <routes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcod\fP"
.br
.ti -1c
.RI "char \fBcity\fP [\fBN\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "char city[\fBN\fP]"
Nome da City 
.SS "int cod"
Código do Vértice 

.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
