.TH "Vertex" 3Trabalho Final EDA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <routes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcod\fP"
.br
.ti -1c
.RI "char \fBcity\fP [\fBN\fP]"
.br
.ti -1c
.RI "bool \fBvisited\fP"
.br
.ti -1c
.RI "struct \fBVertex\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBAdj\fP * \fBadjacents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Descrição de um Vértice do grafo\&. 
.SH "Field Documentation"
.PP 
.SS "struct \fBAdj\fP* adjacents"
Lista de Adjacências 
.SS "char city[\fBN\fP]"
Nome da City 
.SS "int cod"
Código do Vértice 
.SS "struct \fBVertex\fP* next"
Lista de Vértices 
.SS "bool visited"


.SH "Author"
.PP 
Generated automatically by Doxygen for Trabalho Final EDA from the source code\&.
